# OSEMN Exercises

In [1]:
%matplotlib inline
import pandas as pd
import numpy as np

1\. Create a random list of number and then save it to a text file named "simple_data.txt"

In [12]:
l1=np.random.random(100)

#mod1
with open(r"simple_data.txt", "w") as sd:
    for i in l1:
        sd.write("%s\n" % i)
        
#mod2
with open("simple_data2.txt", mode="w") as f:
    for i in l1:
        f.write("%s\n" % i)

2\. Create a random matrix of 5x5 and then save it to a text file named "data.txt"

In [5]:
#failed chiedere a Teo
import numpy as np
import numpy.random as npr
m1=np.matrix(npr.rand(5,5))
print(m1)
print(type(m1))



with open('data.txt') as f:
    for line in m1:
        np.savetxt(f, line, fmt='%.2f')

'''
with open('data.txt','w') as f:
    for i in range(0,5):
        for j in range(0,5):
            f.write(m1[i,j])
        f.write("\n")
'''

#!cat "data.txt"


[[0.45818985 0.56721959 0.50510691 0.14114554 0.23040096]
 [0.44548785 0.19105895 0.80192594 0.03164149 0.29556837]
 [0.47038295 0.6647373  0.49927011 0.20305468 0.36850183]
 [0.94434897 0.93619659 0.82263928 0.73284791 0.03887315]
 [0.20533813 0.60766592 0.78746258 0.82657388 0.39067685]]
<class 'numpy.matrix'>


UnsupportedOperation: not writable

3\. Load the saved txt file of point 2 and convert it to a csv file (by hand)

In [14]:
#da controllare
import csv

with open('data.txt', 'r') as in_file:
    stripped = (line.strip() for line in in_file)
    lines = (line.split(",") for line in stripped if line)
    with open('data.csv', 'w') as out_file:
        writer = csv.writer(out_file)
        writer.writerows(lines)


4\. load the binary file named *credit_card.dat* and convert the data into the real credit-card number.
Each line correspond to a credit card number.
Each character is composed by 6 bit (even the space) and the last 4 bit are just a padding

**hint**: use the `chr()` function to convert a number to a char

5\. Load the file "user_data.json", filter the data by the "CreditCardType" field equals to "American Express". Than save the data a to CSV.

6\. Load the file from this url: [https://www.dropbox.com/s/7u3lm737ogbqsg8/mushrooms_categorized.csv?dl=1](https://www.dropbox.com/s/7u3lm737ogbqsg8/mushrooms_categorized.csv?dl=1) with Pandas. 
+ Explore the data (see the info of the data)
+ Draw the istogram of the 'class' field. Decribe wath yuou see


7\. Load the remote file [https://www.dropbox.com/s/vkl89yce7xjdq4n/regression_generated.csv?dl=1](https://www.dropbox.com/s/vkl89yce7xjdq4n/regression_generated.csv?dl=1) with Pandas and plot a scatter plot all possible combination of the following fields:
    
  + features_1
  + features_2
  + features_3

8\. Load the same file of point 6, and convert the file to json with Pandas.